ARG HA_BASE_IMAGE=ghcr.io/home-assistant/home-assistant:stable
FROM ${HA_BASE_IMAGE}

# We need root to install packages
USER root

# Minimal package installation
RUN \
    apt-get update && \
    apt-get install -y \
      ca-certificates \
      ffmpeg \
      libavcodec-dev \
      libavformat-dev && \
    rm -rf /var/lib/apt/lists/*

# Install faster-whisper
RUN pip install faster-whisper>=0.8.0

# Ensure correct permissions
USER root
