#-------------------------------------------------------------------------------------------------------
#                                                                                                      |
#                                           DOCKER COMPOSE                                             |
#                                                                                                      |
#-------------------------------------------------------------------------------------------------------

services:

  mariadb:
    container_name: jcore_mariadb
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "mb415%"
      MYSQL_DATABASE: "JCORE"
      MYSQL_USER: "mbxxvii"
      MYSQL_PASSWORD: "6wk44!ez#MS2Qhhw"
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3307:3306"

  influxdb:
    container_name: jcore_influxdb
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "mbxxvii"
      DOCKER_INFLUXDB_INIT_PASSWORD: "6wk44!ez#MS2Qhhw"
      DOCKER_INFLUXDB_INIT_ORG: "jia"
      DOCKER_INFLUXDB_INIT_BUCKET: "jcore"
      DOCKER_INFLUXDB_INIT_RETENTION: "90d"

  prometheus:
    container_name: jcore_prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - /opt/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  jia-loki:
    container_name: jcore_loki
    image: grafana/loki:2.9.1
    user: "0:0"
    restart: unless-stopped
    command:
      - "-config.file=/etc/loki/config.yaml"
      - "-log.level=debug"
      - "-target=all"
      - "-config.expand-env=true"
    ports:
      - "3100:3100"
      - "9095:9095"
    volumes:
      - /mnt/docker-data/homeassistant/loki/config/config.yaml:/etc/loki/config.yaml
      - /mnt/docker-data/homeassistant/loki/data:/loki/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  homeassistant:
    container_name: jcore_ha
    image: custom/home-assistant-whisper:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8123:8123"
    environment:
      TZ: "Etc/UTC"
      DOCKER_BUILDKIT: "0"
    volumes:
      - /mnt/docker-data/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mariadb
      - influxdb

  esphome:
    container_name: jcore_esp
    image: ghcr.io/esphome/esphome:2025.5.0b4
    privileged: true
    restart: unless-stopped
    environment:
      TZ: "Etc/UTC"
    volumes:
      - ./esphome:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6052:6052"
    command: >
      dashboard /config
      --address 0.0.0.0
      --port 6052
      --username mbxxvii
      --password mb415%

  mosquitto:
    container_name: jcore_mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  watchtower:
    container_name: jcore_watchtower
    image: containrrr/watchtower:latest
    restart: unless-stopped
    command: --cleanup --interval 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wyoming-piper:
    container_name: jcore_wyoming
    image: rhasspy/wyoming-piper:latest
    restart: unless-stopped
    ports:
      - "10200:10200"
    volumes:
      - ./piper-data:/data
    command:
      - --voice
      - en_US-lessac-medium
      - --uri
      - tcp://0.0.0.0:10200

  terminal:
    container_name: jcore_terminal
    image: tsl0922/ttyd:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "7681:7681"
    volumes:
      - ./config:/config
    command:
      - ttyd
      - -p
      - "7681"
      - bash
    
  filebrowser:
    container_name: jcore_filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      FB_BASEURL: "/"
      HOME: "/config"
    volumes:
      - /mnt/docker-data/homeassistant/config:/srv
      - /mnt/docker-data/homeassistant/filebrowser_config:/config
    command:
      - --root
      - /srv

  npm:
    container_name: jcore_npm
    image: jc21/nginx-proxy-manager:2.11.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "4443:4443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  uptime-kuma:
    container_name: jcore_kuma
    image: louislam/uptime-kuma:1.23.15-alpine
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

  grafana-renderer:
    container_name: jcore_grafana_rdr
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    ports:
      - "8082:8081"

  grafana:
    image: grafana/grafana:latest
    container_name: jcore_grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: "mbxxvii"
      GF_SECURITY_ADMIN_PASSWORD: "mb415%"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "grafana.dreammachine.casa"
      GF_SERVER_ROOT_URL: "https://grafana.dreammachine.casa"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
      GF_RENDERING_SERVER_URL: "http://grafana-renderer:8081"

networks:
  proxy:
    external: true

volumes:
  influxdb-storage:
  influxdb-config:
  grafana-storage:
  uptime-kuma-data:
