---
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/data/index
    cache_location: /loki/data/boltdb-cache
    shared_store: filesystem

  filesystem:
    directory: /loki/data/chunks

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Explicitly disable components
analytics:
  reporting_enabled: false

distributor:
  ring:
    enabled: false

ingester:
  lifecycler:
    ring:
      enabled: false

query_scheduler:
  use_scheduler_ring: false

frontend:
  scheduler_worker_concurrency: 1

querier:
  max_concurrent: 1
  
limits_config:
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  
# Disable ruler and compactor
ruler:
  enable: false

compactor:
  working_directory: /loki/data/compactor
  retention_enabled: false
