# Hetzner API credentials
hetzner_api_token: nRElzSvzwYxEdL8AJUO4D3hJDVzagqdUndQ8jnvpNXufyyRTDMkClAE7Oq8IgN0E
hetzner_server_id: 61655748

# Database credentials
db_password: mb415%
db_user: ha_user
db_name: jcore_production
db_url: mysql://ha_user:ha_password@116.203.14.235:3307/homeassistant?charset=utf8

# InfluxDB credentials
influxdb_token: _-V2KcGrrvN0BbmkiCEdbFKv4ZmKvOW8iSHdJ5BnVQkvVFRT6Th911KzvldhQECGmzRLtzxjndHaEKOE8av79A==
influxdb_org: jia
influxdb_bucket: jcore

# Grafana URL
grafana_host: http://116.203.14.235:3002
