esphome:
  name: jia-sat-vrtl
  friendly_name: JIA SAT-VRTL

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "U3wK1Vgc3ecvDcOYQ+TsuLqrzLIKpJB+7+r2/8EP8a8="

ota:
  - platform: esphome
    password: "75f8787284e8805772300a0f744e320a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jia-Sat-Vrtl Fallback Hotspot"
    password: "Iol3JjRTFwWg"

captive_portal:
    